name: Cache, Build & Test

on:
  push:
    branches: 
      - main

jobs:
  test:

    name: Cache, Build & Test
    env:
      SCHEME: "AlternaFood"
      DEVICE: "iPhone 11"
      DERIVED_DATA_PATH: "DerivedData"

    runs-on: macos-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=14.4,name=iPhone 12']
        
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        id: pods-cache
        with:
            path: Pods
            key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
            restore-keys: |
              ${{ runner.os }}-pods-
              
      - name: Install Pods
        run: |
          pod install
          
      - name: Build and Test
        run: |
          xcodebuild clean test -workspace AlternaFood.xcworkspace -scheme AlternaFood -destination "${destination}" -enableCodeCoverage YES CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
          destination: ${{ matrix.destination }}
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.2.1
