name: SwiftLint

on:
  pull_request:
    branches:
      - main
      - developer
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch base ref
        run: git fetch --no-tags --prune --depth=1 origin ${{ github.ref }}
      - name: Run SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --force-exclude
        env:
          DIFF_BASE: origin/${{ github.ref }}
