name: SwiftLint

on:
  push:
    branches:
      - main
      - developer

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v2
      
      - name: Run linters
        uses: wearerequired/lint-action@master
        with:
          swiftlint: true
          swiftlint_args: "--max-warnings 0"
